steps:
  - name: gcr.io/cloud-builders/git
    args: ['fetch', '--unshallow']
  - name: gcr.io/conventional-github-releaser/conventional-github-releaser:latest
    secretEnv: ['GITHUB_API_TOKEN']
    env:
      - 'APP_VERSION=$SHORT_SHA'
      - 'APP_TAG=$TAG_NAME'
      - 'GITHUB_REPO=$_GITHUB_REPO'
      - 'GITHUB_OWNER=$_GITHUB_OWNER'
  - name: gcr.io/cloud-builders/gcloud-slim
    args: ['container', 'images', 'add-tag', 'gcr.io/$PROJECT_ID/$PROJECT_ID:$SHORT_SHA', 'gcr.io/$PROJECT_ID/$PROJECT_ID:$TAG_NAME', '--quiet']
secrets:
  - kmsKeyName: projects/conventional-github-releaser/locations/us/keyRings/public/cryptoKeys/build
    secretEnv:
      GITHUB_API_TOKEN: CiQAKlHSq2ZcPUqiU+EpTh3YXjm+DF2fSgKVR1tU/YtSXJ1lg64SUQAeWRNUiG2rosvAzy9qoGbMRdgmZp8qVzEXNmvpVM/1vF8m2khk9yj0c+AKAkUoJRMtpeGPQB4olzWEkiOWXjJzjloGUvl0+tghUtMm8AjZqA==
