steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '--pull=true','--tag=gcr.io/$PROJECT_ID/conventional-github-releaser:latest', '--tag=gcr.io/$PROJECT_ID/conventional-github-releaser:$SHORT_SHA', '.']
images: ['gcr.io/$PROJECT_ID/conventional-github-releaser:latest', 'gcr.io/$PROJECT_ID/conventional-github-releaser:$SHORT_SHA']
