steps:
  - name: gcr.io/cloud-builders/git
    args: ['fetch', '--unshallow']
  - name: gcr.io/conventional-github-releaser/conventional-github-releaser:latest
    secretEnv: ['GITHUB_API_TOKEN']
    env:
      - 'APP_VERSION=$SHORT_SHA'
      - 'APP_TAG=$TAG_NAME'
      - 'GITHUB_REPO=$_GITHUB_REPO'
      - 'GITHUB_OWNER=$_GITHUB_OWNER'
  - name: gcr.io/cloud-builders/gcloud-slim
    args: ['container', 'images', 'add-tag', 'gcr.io/$PROJECT_ID/$PROJECT_ID:$SHORT_SHA', 'gcr.io/$PROJECT_ID/$PROJECT_ID:$TAG_NAME', '--quiet']
  - name: gcr.io/cloud-builders/docker
    secretEnv: ['GITHUB_API_TOKEN']
    env:
      - 'GITHUB_REPO=$_GITHUB_REPO'
      - 'GITHUB_OWNER=$_GITHUB_OWNER'
    args: ['login', 'docker.pkg.github.com', '-u', '$GITHUB_OWNER', '-P', '$GITHUB_API_TOKEN']
  - name: gcr.io/cloud-builders/docker
    args: ['pull', 'gcr.io/$PROJECT_ID/$PROJECT_ID:$SHORT_SHA']
  - name: gcr.io/cloud-builders/docker
    env:
      - 'GITHUB_REPO=$_GITHUB_REPO'
      - 'GITHUB_OWNER=$_GITHUB_OWNER'
    args: ['tag', 'gcr.io/$PROJECT_ID/$PROJECT_ID:$SHORT_SHA', 'docker.pkg.github.com/$GITHUB_OWNER/$GITHUB_REPO/$PROJECT_ID:$TAG_NAME']
  - name: gcr.io/cloud-builders/docker
    args: ['tag', 'gcr.io/$PROJECT_ID/$PROJECT_ID:$SHORT_SHA', 'docker.pkg.github.com/$GITHUB_OWNER/$GITHUB_REPO/$PROJECT_ID:$SHORT_SHA']
  - name: gcr.io/cloud-builders/docker
    env:
      - 'GITHUB_REPO=$_GITHUB_REPO'
      - 'GITHUB_OWNER=$_GITHUB_OWNER'
    args: ['push', 'docker.pkg.github.com/$GITHUB_OWNER/$GITHUB_REPO/$PROJECT_ID:$SHORT_SHA']
  - name: gcr.io/cloud-builders/docker
    env:
      - 'GITHUB_REPO=$_GITHUB_REPO'
      - 'GITHUB_OWNER=$_GITHUB_OWNER'
    args: ['push', 'docker.pkg.github.com/$GITHUB_OWNER/$GITHUB_REPO/$PROJECT_ID:$TAG_NAME']
secrets:
  - kmsKeyName: projects/conventional-github-releaser/locations/us/keyRings/public/cryptoKeys/build
    secretEnv:
      GITHUB_API_TOKEN: CiQAfXQzpO9NnOby6YW8EYo6dHN8xo7uX0mW9imXN5wO5E0b5ToSUQBBgo3q1n060PG/oZmvUN3BBzHGyUPkCR6tkLtB7pQqSIwIUJxjjBG6MJSAzfiCMIEz5e2dotVcQmZB6+LnphiV7/Z0zr0Ba+QGvdZ6Qq34KQ==
