steps:
  - name: node:alpine
    entrypoint: yarn
    args: ['install', '--frozen-lockfile']
  - name: node:alpine
    entrypoint: yarn
    args: ['build']
  - name: gcr.io/cloud-builders/docker
    args: ['build', '--pull=true','--tag=eu.gcr.io/$PROJECT_ID/conventional-github-releaser:latest', '--tag=eu.gcr.io/$PROJECT_ID/conventional-github-releaser:$SHORT_SHA', '.']
images: ['eu.gcr.io/$PROJECT_ID/conventional-github-releaser:latest', 'eu.gcr.io/$PROJECT_ID/conventional-github-releaser:$SHORT_SHA']
