name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Create + Publish Image
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build --pull=true --tag=docker.pkg.github.com/$GITHUB_REPOSITORY/conventional-github-releaser:latest --tag=docker.pkg.github.com/$GITHUB_REPOSITORY/conventional-github-releaser:${GITHUB_SHA:0:7} .
