name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Create + Publish Image
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
        name: Get current source code
      - name: Build the Docker image
        run: docker build --pull=true --tag=docker.pkg.github.com/$GITHUB_REPOSITORY/conventional-github-releaser:latest --tag=docker.pkg.github.com/$GITHUB_REPOSITORY/conventional-github-releaser:${GITHUB_SHA:0:7} .
      - name: Login to GitHub Docker Registry
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      - name: Publish "latest" image
        run: docker push docker.pkg.github.com/$GITHUB_REPOSITORY/conventional-github-releaser:latest
      - name: Publish SHA image
        run: docker push docker.pkg.github.com/$GITHUB_REPOSITORY/conventional-github-releaser:${GITHUB_SHA:0:7}
